# Generated by Django 4.2.29 on 2026-04-02 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_add_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRejected",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=150)),
                ("user_type", models.CharField(default="Admin", max_length=10)),
                ("rejected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "userrejected",
                "ordering": ["-rejected_at"],
            },
        ),
    ]
