# Generated by Django 4.2.29 on 2026-04-02 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_add_userrejected_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrejected",
            name="rejected_by",
        ),
        migrations.RemoveIndex(
            model_name="adminapprovalrequest",
            name="idx_approval_status_created",
        ),
        migrations.RemoveIndex(
            model_name="deletedrecordsbackup",
            name="idx_deleted_type_time",
        ),
        migrations.AlterField(
            model_name="adminapprovalrequest",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_request",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="adminapprovalrequest",
            index=models.Index(
                fields=["status", "created_at"], name="idx_approval_status_created"
            ),
        ),
        migrations.AddIndex(
            model_name="deletedrecordsbackup",
            index=models.Index(
                fields=["record_type", "deleted_at"], name="idx_deleted_type_time"
            ),
        ),
        migrations.DeleteModel(
            name="UserRejected",
        ),
    ]
