# Generated by Django 4.2.29 on 2026-04-02 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_fix_approval_indexes_mssql"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResetAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_type",
                    models.CharField(
                        choices=[
                            ("code_verify", "Code Verification"),
                            ("email_reset", "Email Reset"),
                            ("password_change", "Password Change"),
                        ],
                        default="code_verify",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("was_successful", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reset_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"], name="idx_reset_attempt_user_t"
                    ),
                    models.Index(
                        fields=["attempt_type"], name="idx_reset_attempt_type"
                    ),
                ],
            },
        ),
    ]
