# Generated by Django 4.2.29 on 2026-04-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0009_productmodel_supplier_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("STOCK_ADJUST", "Stock Adjustment"),
                            ("SALE", "Sale"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("APPROVAL", "Approval"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("sale", "Sale"),
                            ("user", "User"),
                            ("stock", "Stock"),
                            ("order", "Order"),
                            ("auth", "Authentication"),
                            ("system", "System"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_id", models.CharField(blank=True, default="", max_length=50)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "activity_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["action", "timestamp"], name="idx_actlog_action_time"
                    ),
                    models.Index(
                        fields=["target_type", "timestamp"],
                        name="idx_actlog_target_time",
                    ),
                ],
            },
        ),
    ]
